-- Drop the old table
DROP TABLE workflows;

CREATE TABLE workflows (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  data TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id),
  created_at INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
