import { NodeRegistry } from "./workflowTypes";
import { BartLargeCnnNode } from "./nodes/text/bartLargeCnnNode";
import { DistilbertSst2Int8Node } from "./nodes/text/distilbertSst2Int8Node";
import { M2m10012bNode } from "./nodes/text/m2m10012bNode";
import { StableDiffusionXLLightningNode } from "./nodes/image/stableDiffusionXLLightningNode";
import { StableDiffusionV15Img2ImgNode } from "./nodes/image/stableDiffusionV15Img2ImgNode";
import { Resnet50Node } from "./nodes/image/resnet50Node";
import { StableDiffusionXLBase10Node } from "./nodes/image/stableDiffusionXLBase10Node";
import { Flux1SchnellNode } from "./nodes/image/flux1SchnellNode";
import { DreamShaper8LCMNode } from "./nodes/image/dreamShaper8LCMNode";
import { UformGen2Qwen500mNode } from "./nodes/image/uformGen2Qwen500mNode";
import { ImageUrlLoaderNode } from "./nodes/image/imageUrlLoaderNode";
import { JsonStringExtractorNode } from "./nodes/json/jsonStringExtractorNode";
import { JsonBooleanExtractorNode } from "./nodes/json/jsonBooleanExtractorNode";
import { JsonNumberExtractorNode } from "./nodes/json/jsonNumberExtractorNode";
import { JsonObjectArrayExtractorNode } from "./nodes/json/jsonObjectArrayExtractorNode";
import { StringTemplateNode } from "./nodes/text/stringTemplateNode";
import { AdditionNode } from "./nodes/number/additionNode";
import { SubtractionNode } from "./nodes/number/subtractionNode";
import { MultiplicationNode } from "./nodes/number/multiplicationNode";
import { DivisionNode } from "./nodes/number/divisionNode";
import { ModuloNode } from "./nodes/number/moduloNode";
import { ExponentiationNode } from "./nodes/number/exponentiationNode";
import { SquareRootNode } from "./nodes/number/squareRootNode";
import { AbsoluteValueNode } from "./nodes/number/absoluteValueNode";
import { SliderNode } from "./nodes/number/sliderNode";
import { Llama318BInstructFastNode } from "./nodes/text/llama318BInstructFastNode";
import { WhisperNode } from "./nodes/audio/whisperNode";
import { LLaVA157BHFNode } from "./nodes/image/llava157BHFNode";
import { RadioGroupNode } from "./nodes/text/radioGroupNode";
import { TextAreaNode } from "./nodes/text/textAreaNode";
import { InputTextNode } from "./nodes/text/inputTextNode";
import { NumberInputNode } from "./nodes/number/numberInputNode";
import { MonacoEditorNode } from "./nodes/json/monacoEditorNode";
import { CanvasDoodleNode } from "./nodes/image/canvasDoodleNode";
import { WebcamNode } from "./nodes/image/webcamNode";
import { AudioRecorderNode } from "./nodes/audio/audioRecorderNode";
import { DetrResnet50Node } from "./nodes/image/detrResnet50Node";
import { MelottsNode } from "./nodes/audio/melottsNode";
import { BgeRerankerBaseNode } from "./nodes/text/bgeRerankerBaseNode";
import { WhisperLargeV3TurboNode } from "./nodes/audio/whisperLargeV3TurboNode";
import { WhisperTinyEnNode } from "./nodes/audio/whisperTinyEnNode";

/**
 * Register the mathematical operation nodes
 */
export function registerNodes(): void {
  const registry = NodeRegistry.getInstance();

  registry.registerImplementation(AdditionNode);
  registry.registerImplementation(SubtractionNode);
  registry.registerImplementation(MultiplicationNode);
  registry.registerImplementation(DivisionNode);
  registry.registerImplementation(ModuloNode);
  registry.registerImplementation(ExponentiationNode);
  registry.registerImplementation(SquareRootNode);
  registry.registerImplementation(AbsoluteValueNode);
  registry.registerImplementation(RadioGroupNode);
  registry.registerImplementation(TextAreaNode);
  registry.registerImplementation(InputTextNode);
  registry.registerImplementation(NumberInputNode);
  registry.registerImplementation(SliderNode);
  registry.registerImplementation(Llama318BInstructFastNode);
  registry.registerImplementation(WhisperNode);
  registry.registerImplementation(WhisperLargeV3TurboNode);
  registry.registerImplementation(WhisperTinyEnNode);
  registry.registerImplementation(UformGen2Qwen500mNode);
  registry.registerImplementation(BartLargeCnnNode);
  registry.registerImplementation(M2m10012bNode);
  registry.registerImplementation(DistilbertSst2Int8Node);
  registry.registerImplementation(BgeRerankerBaseNode);
  registry.registerImplementation(DetrResnet50Node);
  registry.registerImplementation(Resnet50Node);
  registry.registerImplementation(ImageUrlLoaderNode);
  registry.registerImplementation(StableDiffusionXLLightningNode);
  registry.registerImplementation(StableDiffusionV15Img2ImgNode);
  registry.registerImplementation(JsonStringExtractorNode);
  registry.registerImplementation(JsonBooleanExtractorNode);
  registry.registerImplementation(JsonNumberExtractorNode);
  registry.registerImplementation(JsonObjectArrayExtractorNode);
  registry.registerImplementation(StringTemplateNode);
  registry.registerImplementation(MonacoEditorNode);
  registry.registerImplementation(LLaVA157BHFNode);
  registry.registerImplementation(CanvasDoodleNode);
  registry.registerImplementation(StableDiffusionXLBase10Node);
  registry.registerImplementation(Flux1SchnellNode);
  registry.registerImplementation(DreamShaper8LCMNode);
  registry.registerImplementation(MelottsNode);
  registry.registerImplementation(WebcamNode);
  registry.registerImplementation(AudioRecorderNode);
}
