import { NodeRegistry } from "../runtimeRegistries";
import { BartLargeCnnNode } from "./text/bartLargeCnnNode";
import { DistilbertSst2Int8Node } from "./text/distilbertSst2Int8Node";
import { M2m10012bNode } from "./text/m2m10012bNode";
import { StableDiffusionXLLightningNode } from "./image/stableDiffusionXLLightningNode";
import { StableDiffusionV15Img2ImgNode } from "./image/stableDiffusionV15Img2ImgNode";
import { Resnet50Node } from "./image/resnet50Node";
import { StableDiffusionXLBase10Node } from "./image/stableDiffusionXLBase10Node";
import { Flux1SchnellNode } from "./image/flux1SchnellNode";
import { DreamShaper8LCMNode } from "./image/dreamShaper8LCMNode";
import { UformGen2Qwen500mNode } from "./image/uformGen2Qwen500mNode";
import { ImageUrlLoaderNode } from "./image/imageUrlLoaderNode";
import { JsonStringExtractorNode } from "./json/jsonStringExtractorNode";
import { JsonBooleanExtractorNode } from "./json/jsonBooleanExtractorNode";
import { JsonNumberExtractorNode } from "./json/jsonNumberExtractorNode";
import { JsonObjectArrayExtractorNode } from "./json/jsonObjectArrayExtractorNode";
import { StringTemplateNode } from "./text/stringTemplateNode";
import { SimpleStringTemplateNode } from "./text/simpleStringTemplateNode";
import { AdditionNode } from "./number/additionNode";
import { SubtractionNode } from "./number/subtractionNode";
import { MultiplicationNode } from "./number/multiplicationNode";
import { DivisionNode } from "./number/divisionNode";
import { ModuloNode } from "./number/moduloNode";
import { ExponentiationNode } from "./number/exponentiationNode";
import { SquareRootNode } from "./number/squareRootNode";
import { AbsoluteValueNode } from "./number/absoluteValueNode";
import { SliderNode } from "./number/sliderNode";
import { Llama318BInstructFastNode } from "./text/llama318BInstructFastNode";
import { WhisperNode } from "./audio/whisperNode";
import { LLaVA157BHFNode } from "./image/llava157BHFNode";
import { RadioGroupNode } from "./text/radioGroupNode";
import { TextAreaNode } from "./text/textAreaNode";
import { InputTextNode } from "./text/inputTextNode";
import { NumberInputNode } from "./number/numberInputNode";
import { MonacoEditorNode } from "./json/monacoEditorNode";
import { CanvasDoodleNode } from "./image/canvasDoodleNode";
import { WebcamNode } from "./image/webcamNode";
import { AudioRecorderNode } from "./audio/audioRecorderNode";
import { DetrResnet50Node } from "./image/detrResnet50Node";
import { MelottsNode } from "./audio/melottsNode";
import { BgeRerankerBaseNode } from "./text/bgeRerankerBaseNode";
import { WhisperLargeV3TurboNode } from "./audio/whisperLargeV3TurboNode";
import { WhisperTinyEnNode } from "./audio/whisperTinyEnNode";
import { StableDiffusionV15InpaintingNode } from "./image/stableDiffusionV15InpaintingNode";
import { JsonTemplateNode } from "./json/jsonTemplateNode";
/**
 * Register the mathematical operation nodes
 */
export function registerNodes(): void {
  const registry = NodeRegistry.getInstance();

  registry.registerImplementation(AdditionNode);
  registry.registerImplementation(SubtractionNode);
  registry.registerImplementation(MultiplicationNode);
  registry.registerImplementation(DivisionNode);
  registry.registerImplementation(ModuloNode);
  registry.registerImplementation(ExponentiationNode);
  registry.registerImplementation(SquareRootNode);
  registry.registerImplementation(AbsoluteValueNode);
  registry.registerImplementation(RadioGroupNode);
  registry.registerImplementation(TextAreaNode);
  registry.registerImplementation(InputTextNode);
  registry.registerImplementation(NumberInputNode);
  registry.registerImplementation(SliderNode);
  registry.registerImplementation(Llama318BInstructFastNode);
  registry.registerImplementation(WhisperNode);
  registry.registerImplementation(WhisperLargeV3TurboNode);
  registry.registerImplementation(WhisperTinyEnNode);
  registry.registerImplementation(UformGen2Qwen500mNode);
  registry.registerImplementation(BartLargeCnnNode);
  registry.registerImplementation(M2m10012bNode);
  registry.registerImplementation(DistilbertSst2Int8Node);
  registry.registerImplementation(BgeRerankerBaseNode);
  registry.registerImplementation(DetrResnet50Node);
  registry.registerImplementation(Resnet50Node);
  registry.registerImplementation(ImageUrlLoaderNode);
  registry.registerImplementation(StableDiffusionXLLightningNode);
  registry.registerImplementation(StableDiffusionV15Img2ImgNode);
  registry.registerImplementation(StableDiffusionV15InpaintingNode);
  registry.registerImplementation(JsonStringExtractorNode);
  registry.registerImplementation(JsonBooleanExtractorNode);
  registry.registerImplementation(JsonNumberExtractorNode);
  registry.registerImplementation(JsonObjectArrayExtractorNode);
  registry.registerImplementation(JsonTemplateNode);
  registry.registerImplementation(StringTemplateNode);
  registry.registerImplementation(SimpleStringTemplateNode);
  registry.registerImplementation(MonacoEditorNode);
  registry.registerImplementation(LLaVA157BHFNode);
  registry.registerImplementation(CanvasDoodleNode);
  registry.registerImplementation(StableDiffusionXLBase10Node);
  registry.registerImplementation(Flux1SchnellNode);
  registry.registerImplementation(DreamShaper8LCMNode);
  registry.registerImplementation(MelottsNode);
  registry.registerImplementation(WebcamNode);
  registry.registerImplementation(AudioRecorderNode);
}
