CREATE TABLE IF NOT EXISTS "platform_ai_model_channels" (
  "canonical_id" text NOT NULL REFERENCES "platform_ai_models"("canonical_id") ON DELETE CASCADE,
  "channel" text NOT NULL,
  "preset_id" text NOT NULL,
  "upstream_model_id" text NOT NULL,
  "channel_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("canonical_id", "channel")
);

INSERT INTO "platform_ai_model_channels" (
  "canonical_id",
  "channel",
  "preset_id",
  "upstream_model_id",
  "channel_enabled"
) VALUES
  ('doubao-seed-evolving', 'aggregate', 'aggregate:volcano', 'doubao-seed-evolving', true),
  ('deepseek-v4-pro', 'aggregate', 'aggregate:volcano', 'deepseek-v4-pro-260425', true),
  ('deepseek-v4-flash', 'aggregate', 'aggregate:volcano', 'deepseek-v4-flash-260425', true),
  ('glm-5-2', 'aggregate', 'aggregate:volcano', 'glm-5-2-260617', true),
  ('doubao-seedance-2', 'aggregate', 'aggregate:volcano', 'doubao-seedance-2-0-260128', true),
  ('doubao-seedance-2-fast', 'aggregate', 'aggregate:volcano', 'doubao-seedance-2-0-fast-260128', true),
  ('doubao-seedance-2-mini', 'aggregate', 'aggregate:volcano', 'doubao-seedance-2-0-mini-260615', true),
  ('doubao-seedream-5', 'aggregate', 'aggregate:volcano', 'doubao-seedream-5-0-260128', true),
  ('deepseek-v4-pro', 'api', 'provider:deepseek', 'deepseek-v4-pro', true),
  ('deepseek-v4-flash', 'api', 'provider:deepseek', 'deepseek-v4-flash', true),
  ('doubao-seedance-2', 'api', 'provider:seedance', 'doubao-seedance-2-0-260128', true),
  ('doubao-seedance-2-fast', 'api', 'provider:seedance', 'doubao-seedance-2-0-fast-260128', true),
  ('doubao-seedance-2-mini', 'api', 'provider:seedance', 'doubao-seedance-2-0-mini-260615', true),
  ('doubao-seedance-2-5', 'api', 'provider:seedance', 'doubao-seedance-2-5-260628', true),
  ('doubao-seedream-5', 'api', 'provider:seedream', 'doubao-seedream-5-0-260128', true),
  ('doubao-seed-evolving', 'api', 'provider:seed', 'doubao-seed-evolving', true),
  ('glm-5-2', 'api', 'provider:glm', 'glm-5-2-260617', true),
  ('kimi-k3', 'api', 'provider:kimi', 'kimi-k3', true),
  ('kimi-k2.6', 'api', 'provider:kimi', 'kimi-k2.6', true),
  ('kimi-k2.5', 'api', 'provider:kimi', 'kimi-k2.5', true),
  ('gpt-5-6-sol', 'api', 'provider:openai', 'gpt-5.6-sol', true),
  ('gpt-5-6-terra', 'api', 'provider:openai', 'gpt-5.6-terra', true),
  ('gpt-5-6-luna', 'api', 'provider:openai', 'gpt-5.6-luna', true),
  ('gpt-image-2', 'api', 'provider:openai-image', 'gpt-image-2', true),
  ('gemini-3-5-flash', 'api', 'provider:gemini', 'gemini-3.5-flash', true),
  ('gemini-3-6-flash', 'api', 'provider:gemini', 'gemini-3.6-flash', true),
  ('gemini-3-5-flash-lite', 'api', 'provider:gemini', 'gemini-3.5-flash-lite', true),
  ('gemini-3-1-flash-image', 'api', 'provider:nano-banana', 'gemini-3.1-flash-image', true),
  ('gemini-3-1-flash-lite-image', 'api', 'provider:nano-banana', 'gemini-3.1-flash-lite-image', true),
  ('gemini-3-pro-image', 'api', 'provider:nano-banana', 'gemini-3-pro-image', true),
  ('veo-3-1-generate', 'api', 'provider:veo', 'veo-3.1-generate-preview', true),
  ('veo-3-1-fast-generate', 'api', 'provider:veo', 'veo-3.1-fast-generate-preview', true),
  ('veo-3-1-lite-generate', 'api', 'provider:veo', 'veo-3.1-lite-generate-preview', true),
  ('grok-4-5', 'api', 'provider:grok', 'grok-4.5', true),
  ('grok-4-3', 'api', 'provider:grok', 'grok-4.3', true),
  ('grok-imagine-image', 'api', 'provider:grok-imagine-image', 'grok-imagine-image', true),
  ('grok-imagine-image-quality', 'api', 'provider:grok-imagine-image', 'grok-imagine-image-quality', true),
  ('grok-imagine-video', 'api', 'provider:grok-imagine-video', 'grok-imagine-video', true),
  ('grok-imagine-video-1-5', 'api', 'provider:grok-imagine-video', 'grok-imagine-video-1.5', true),
  ('claude-sonnet-5', 'api', 'provider:claude', 'claude-sonnet-5', true),
  ('claude-opus-5', 'api', 'provider:claude', 'claude-opus-5', true),
  ('claude-haiku-4-5', 'api', 'provider:claude', 'claude-haiku-4-5', true),
  ('minimax-speech-2-8-hd', 'api', 'provider:minimax-speech', 'speech-2.8-hd', true),
  ('minimax-speech-2-8-turbo', 'api', 'provider:minimax-speech', 'speech-2.8-turbo', true)
ON CONFLICT ("canonical_id", "channel") DO NOTHING;
