/**
 * Minimal YAML subset parser for containers/app.yml.
 * Supports: scalars, booleans, numbers, and a single-level `env:` map.
 */

/**
 * @param {string} raw
 * @returns {{
 *   hostname: string,
 *   https: boolean,
 *   tls: 'auto' | 'fallback' | 'manual',
 *   le_email: string,
 *   http_port: number,
 *   https_port: number,
 *   env: Record<string, string>
 * }}
 */
export function parseAppYml(raw) {
  /** @type {Record<string, string>} */
  const env = {};
  /** @type {Record<string, string | boolean | number>} */
  const root = {};

  let inEnv = false;
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    if (!line.startsWith(" ") && !line.startsWith("\t") && trimmed.endsWith(":")) {
      const key = trimmed.slice(0, -1).trim();
      inEnv = key === "env";
      continue;
    }

    if (inEnv && (line.startsWith(" ") || line.startsWith("\t"))) {
      const withoutIndent = trimmed;
      const sep = withoutIndent.indexOf(":");
      if (sep === -1) {
        continue;
      }
      const key = withoutIndent.slice(0, sep).trim();
      const value = stripQuotes(withoutIndent.slice(sep + 1).trim());
      if (key) {
        env[key] = value;
      }
      continue;
    }

    inEnv = false;
    const sep = trimmed.indexOf(":");
    if (sep === -1) {
      continue;
    }
    const key = trimmed.slice(0, sep).trim();
    const valueRaw = stripQuotes(trimmed.slice(sep + 1).trim());
    if (key === "env") {
      inEnv = true;
      continue;
    }
    root[key] = coerce(valueRaw);
  }

  const hostname = String(root.hostname ?? "").trim();
  if (!hostname) {
    throw new Error("containers/app.yml: hostname is required");
  }

  const tlsRaw = String(root.tls ?? "auto").trim().toLowerCase();
  let tls = "auto";
  if (tlsRaw === "fallback" || tlsRaw === "acme") {
    tls = "fallback";
  } else if (tlsRaw === "manual") {
    tls = "manual";
  }

  return {
    hostname,
    https: root.https === undefined ? true : Boolean(root.https),
    tls,
    le_email: String(root.le_email ?? "").trim(),
    http_port: Number(root.http_port ?? 80) || 80,
    https_port: Number(root.https_port ?? 443) || 443,
    env,
  };
}

/**
 * @param {string} value
 */
function stripQuotes(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

/**
 * @param {string} value
 * @returns {string | boolean | number}
 */
function coerce(value) {
  if (value === "true") {
    return true;
  }
  if (value === "false") {
    return false;
  }
  if (value !== "" && !Number.isNaN(Number(value)) && /^-?\d+$/.test(value)) {
    return Number(value);
  }
  return value;
}

/**
 * @param {{
 *   hostname: string,
 *   https: boolean,
 *   tls?: 'auto' | 'fallback' | 'manual',
 *   le_email?: string,
 *   http_port?: number,
 *   https_port?: number,
 *   env: Record<string, string>
 * }} config
 */
export function stringifyAppYml(config) {
  const lines = [
    "# Generated by dafthunk-setup — do not commit",
    `hostname: ${config.hostname}`,
    `https: ${config.https ? "true" : "false"}`,
    `tls: ${config.tls ?? "auto"}`,
  ];
  if (config.le_email) {
    lines.push(`le_email: ${config.le_email}`);
  }
  lines.push(`http_port: ${config.http_port ?? 80}`);
  lines.push(`https_port: ${config.https_port ?? 443}`);
  lines.push("env:");
  for (const [key, value] of Object.entries(config.env)) {
    lines.push(`  ${key}: ${escapeYmlScalar(value)}`);
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * @param {string} value
 */
function escapeYmlScalar(value) {
  if (/[:#{}[\],&*?|>!%@`]/.test(value) || value.includes(" ")) {
    return JSON.stringify(value);
  }
  return value;
}
