import fs from "node:fs";
import path from "node:path";

import { parseAppYml } from "./parse-app-yml.mjs";
import {
  appYmlPath,
  dockerHostRoot,
  ensureHostDirs,
  generatedCaddyfilePath,
  generatedComposePath,
  generatedEnvPath,
  repoRoot,
} from "./paths.mjs";
import { isPlaceholderSecret } from "./secrets.mjs";

/**
 * @param {string} hostname
 * @param {boolean} https
 * @param {number} httpPort
 * @param {number} httpsPort
 */
export function publicOrigin(hostname, https, httpPort = 80, httpsPort = 443) {
  if (https) {
    if (httpsPort !== 443) {
      return `https://${hostname}:${httpsPort}`;
    }
    return `https://${hostname}`;
  }
  if (httpPort !== 80) {
    return `http://${hostname}:${httpPort}`;
  }
  return `http://${hostname}`;
}

/**
 * @returns {ReturnType<typeof parseAppYml> & { origin: string }}
 */
export function loadAppConfig() {
  if (!fs.existsSync(appYmlPath)) {
    throw new Error(
      `Missing ${path.relative(repoRoot, appYmlPath)}. Run: node docker-host/dafthunk-setup.mjs`
    );
  }
  const config = parseAppYml(fs.readFileSync(appYmlPath, "utf8"));
  for (const key of ["JWT_SECRET", "SECRET_MASTER_KEY"]) {
    if (isPlaceholderSecret(config.env[key])) {
      throw new Error(
        `containers/app.yml: ${key} is still a placeholder. Re-run dafthunk-setup.`
      );
    }
  }
  const origin =
    config.env.WEB_HOST?.trim() ||
    publicOrigin(
      config.hostname,
      config.https,
      config.http_port,
      config.https_port
    );
  return {
    ...config,
    origin,
  };
}

/**
 * @param {ReturnType<typeof loadAppConfig>} config
 */
export function renderCaddyfile(config) {
  const siteHandler = `	handle_path /api/* {
		reverse_proxy api:3102
	}
	handle {
		reverse_proxy app:80
	}`;

  if (config.https) {
    const global = config.le_email
      ? `{\n\temail ${config.le_email}\n}\n\n`
      : "";
    return `${global}${config.hostname} {
${siteHandler}
}
`;
  }

  // HTTP-only: listen on :80 in-container; host maps http_port → 80
  return `:80 {
${siteHandler}
}
`;
}

/**
 * @param {ReturnType<typeof loadAppConfig>} config
 */
export function renderCompose(config) {
  const origin = config.origin.replace(/\/$/, "");
  const marketingOrigin = `${origin}/m`;
  const gatewayConf = "../docker/nginx/app.gateway.conf";

  return `# Generated by docker-host/launcher — do not edit
name: dafthunk-host

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./shared/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod-api
      args:
        NODE_VERSION: "22.12.0"
        PNPM_VERSION: "10.3.0"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: "3102"
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      LOCAL_STORAGE_PATH: /app/data/storage
      RUN_DB_MIGRATE: "true"
      WEB_HOST: "${origin}"
      WEBSITE_URL: "${marketingOrigin}"
      JWT_SECRET: \${JWT_SECRET}
      SECRET_MASTER_KEY: \${SECRET_MASTER_KEY}
      CLOUDFLARE_ENV: production
    volumes:
      - ./shared/storage:/app/data/storage
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \\"fetch('http://127.0.0.1:3102/health').then((r)=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    restart: unless-stopped

  www:
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod-www
      args:
        NODE_VERSION: "22.12.0"
        PNPM_VERSION: "10.3.0"
        VITE_API_HOST: /api
        VITE_APP_URL: "${origin}"
        VITE_WEBSITE_URL: "${marketingOrigin}"
        VITE_WWW_BASENAME: "/m"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod-app
      args:
        NODE_VERSION: "22.12.0"
        PNPM_VERSION: "10.3.0"
        VITE_API_HOST: /api
        VITE_APP_URL: "${origin}"
        VITE_WEBSITE_URL: "${marketingOrigin}"
        VITE_WS_VIA_PROXY: "1"
    depends_on:
      api:
        condition: service_healthy
      www:
        condition: service_started
    volumes:
      - ${gatewayConf}:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  caddy:
    image: caddy:2.9-alpine
    depends_on:
      - app
      - api
      - www
    ports:
      - "\${HTTP_PORT:-${config.http_port}}:80"
      - "\${HTTPS_PORT:-${config.https_port}}:443"
      - "\${HTTPS_PORT:-${config.https_port}}:443/udp"
    volumes:
      - ./Caddyfile.generated:/etc/caddy/Caddyfile:ro
      - ./shared/caddy:/data
      - ./shared/caddy-config:/config
    restart: unless-stopped
`;
}

/**
 * @param {ReturnType<typeof loadAppConfig>} config
 */
export function renderEnvFile(config) {
  return [
    "# Generated by docker-host/launcher — do not commit",
    `JWT_SECRET=${config.env.JWT_SECRET}`,
    `SECRET_MASTER_KEY=${config.env.SECRET_MASTER_KEY}`,
    `HTTP_PORT=${config.http_port}`,
    `HTTPS_PORT=${config.https_port}`,
    "",
  ].join("\n");
}

export function writeGeneratedFiles() {
  ensureHostDirs();
  fs.mkdirSync(path.join(dockerHostRoot, "shared", "caddy-config"), {
    recursive: true,
  });
  const config = loadAppConfig();
  fs.writeFileSync(generatedCaddyfilePath, renderCaddyfile(config), "utf8");
  fs.writeFileSync(generatedComposePath, renderCompose(config), "utf8");
  fs.writeFileSync(generatedEnvPath, renderEnvFile(config), "utf8");
  return config;
}
