#!/usr/bin/env bash
# Step 2: Write docker-host/containers/app.yml
#   sudo DAFTHUNK_HOSTNAME=your.domain /var/dafthunk/scripts/host/configure.sh
#   sudo bash configure.sh --http   # HTTP only (no TLS)
set -euo pipefail

INSTALL_DIR="${DAFTHUNK_INSTALL_DIR:-/var/dafthunk}"
HOST_DIR="${INSTALL_DIR}/docker-host"
APP_YML="${HOST_DIR}/containers/app.yml"
HOSTNAME="${DAFTHUNK_HOSTNAME:-}"
FORCE=0
USE_HTTP=0

log() { printf '==> %s\n' "$*"; }
info() { printf ' -> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --http) USE_HTTP=1; shift ;;
    -h|--help)
      echo "Usage: sudo [DAFTHUNK_HOSTNAME=domain] $0 [--force] [--http]"
      exit 0
      ;;
    *) die "Unknown option: $1" ;;
  esac
done

[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "Run as root (sudo)"
[[ -d "$INSTALL_DIR" ]] || die "Run bootstrap.sh first"

if [[ -f "$APP_YML" && "$FORCE" != "1" ]]; then
  info "Config exists: $APP_YML (use --force to overwrite)"
  exit 0
fi

read_hostname() {
  [[ -n "$HOSTNAME" ]] && return 0
  [[ -r /dev/tty && -w /dev/tty ]] || die "Set DAFTHUNK_HOSTNAME or use an SSH session with TTY"
  printf '公网域名: ' >/dev/tty
  read -r HOSTNAME </dev/tty || die "Could not read domain"
  HOSTNAME="${HOSTNAME#"${HOSTNAME%%[![:space:]]*}"}"
  HOSTNAME="${HOSTNAME%"${HOSTNAME##*[![:space:]]}"}"
  [[ -n "$HOSTNAME" ]] || die "Domain cannot be empty"
}

hex_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

log "Configure"
read_hostname
mkdir -p "${HOST_DIR}/containers" "${HOST_DIR}/shared/postgres" "${HOST_DIR}/shared/storage" "${HOST_DIR}/shared/caddy"

jwt="$(hex_secret)"
master="$(hex_secret)"
if [[ "$USE_HTTP" == "1" ]]; then
  web_host="http://${HOSTNAME}"
  https_yaml="false"
else
  web_host="https://${HOSTNAME}"
  https_yaml="true"
fi

cat >"$APP_YML" <<EOF
# Generated by scripts/host/configure.sh — do not commit
hostname: ${HOSTNAME}
https: ${https_yaml}
http_port: 80
https_port: 443
env:
  JWT_SECRET: ${jwt}
  SECRET_MASTER_KEY: ${master}
  WEB_HOST: ${web_host}
  WEBSITE_URL: ${web_host}
EOF

info "Wrote $APP_YML"
info "Site: $web_host"
info "Next: sudo bash ${INSTALL_DIR}/scripts/host/deploy.sh"
